//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoLockScreenHelper2.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lng {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lng() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NoLockScreenHelper2.Resources.Lng", typeof(Lng).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktivováno.
        /// </summary>
        internal static string Activated {
            get {
                return ResourceManager.GetString("Activated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AUTO.
        /// </summary>
        internal static string Auto {
            get {
                return ResourceManager.GetString("Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Při běhu programu nastala chyba.
        /// </summary>
        internal static string ExceptionDuringRunningProgram {
            get {
                return ResourceManager.GetString("ExceptionDuringRunningProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Česky.
        /// </summary>
        internal static string LangCzech {
            get {
                return ResourceManager.GetString("LangCzech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string LangEnglish {
            get {
                return ResourceManager.GetString("LangEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zrušit.
        /// </summary>
        internal static string NetEditFrmButtonCancel {
            get {
                return ResourceManager.GetString("NetEditFrmButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budiž.
        /// </summary>
        internal static string NetEditFrmButtonOk {
            get {
                return ResourceManager.GetString("NetEditFrmButtonOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zvolte položku.
        /// </summary>
        internal static string NetEditFrmComboBoxChooseNet {
            get {
                return ResourceManager.GetString("NetEditFrmComboBoxChooseNet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Úprava sítě.
        /// </summary>
        internal static string NetEditFrmFormName {
            get {
                return ResourceManager.GetString("NetEditFrmFormName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vyberte jednu z nalezených sítí.
        /// </summary>
        internal static string NetEditFrmLabelChooseNet {
            get {
                return ResourceManager.GetString("NetEditFrmLabelChooseNet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Brány.
        /// </summary>
        internal static string NetEditFrmLabelGateway {
            get {
                return ResourceManager.GetString("NetEditFrmLabelGateway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Adresa.
        /// </summary>
        internal static string NetEditFrmLabelIPAddress {
            get {
                return ResourceManager.GetString("NetEditFrmLabelIPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Název.
        /// </summary>
        internal static string NetEditFrmLabelName {
            get {
                return ResourceManager.GetString("NetEditFrmLabelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Název síťe.
        /// </summary>
        internal static string NetEditFrmLabelNetworkName {
            get {
                return ResourceManager.GetString("NetEditFrmLabelNetworkName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktivovat při startu.
        /// </summary>
        internal static string SettingsActivateOnStartup {
            get {
                return ResourceManager.GetString("SettingsActivateOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přidat.
        /// </summary>
        internal static string SettingsAdd {
            get {
                return ResourceManager.GetString("SettingsAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zrušit přenositelnost.
        /// </summary>
        internal static string SettingsButtonPortableMakerDisable {
            get {
                return ResourceManager.GetString("SettingsButtonPortableMakerDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Udělat přenositelné.
        /// </summary>
        internal static string SettingsButtonPortableMakerEnable {
            get {
                return ResourceManager.GetString("SettingsButtonPortableMakerEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Povolit informační bubliny.
        /// </summary>
        internal static string SettingsEnableNotificationBubbles {
            get {
                return ResourceManager.GetString("SettingsEnableNotificationBubbles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jazyk.
        /// </summary>
        internal static string SettingsGroupBoxLanguage {
            get {
                return ResourceManager.GetString("SettingsGroupBoxLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Přenositelnost.
        /// </summary>
        internal static string SettingsGroupBoxPortability {
            get {
                return ResourceManager.GetString("SettingsGroupBoxPortability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Časovač.
        /// </summary>
        internal static string SettingsGroupBoxTimer {
            get {
                return ResourceManager.GetString("SettingsGroupBoxTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Když časovač skončí.
        /// </summary>
        internal static string SettingsGroupBoxTimerEnds {
            get {
                return ResourceManager.GetString("SettingsGroupBoxTimerEnds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schovat při minimalizaci.
        /// </summary>
        internal static string SettingsHideIfMinimized {
            get {
                return ResourceManager.GetString("SettingsHideIfMinimized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Brány.
        /// </summary>
        internal static string SettingsOLVColGateway {
            get {
                return ResourceManager.GetString("SettingsOLVColGateway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Adresa.
        /// </summary>
        internal static string SettingsOLVColIPAddress {
            get {
                return ResourceManager.GetString("SettingsOLVColIPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Název.
        /// </summary>
        internal static string SettingsOLVColName {
            get {
                return ResourceManager.GetString("SettingsOLVColName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Název sítě.
        /// </summary>
        internal static string SettingsOLVColNetworkName {
            get {
                return ResourceManager.GetString("SettingsOLVColNetworkName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Čas.
        /// </summary>
        internal static string SettingsOLVColTimerTimeSpan {
            get {
                return ResourceManager.GetString("SettingsOLVColTimerTimeSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to přeponout na Auto.
        /// </summary>
        internal static string SettingsRadioButtonTimerEndsAuto {
            get {
                return ResourceManager.GetString("SettingsRadioButtonTimerEndsAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to přepnout na Stop.
        /// </summary>
        internal static string SettingsRadioButtonTimerEndsStop {
            get {
                return ResourceManager.GetString("SettingsRadioButtonTimerEndsStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odebrat.
        /// </summary>
        internal static string SettingsRemove {
            get {
                return ResourceManager.GetString("SettingsRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spustit při přihlášení.
        /// </summary>
        internal static string SettingsRunOnLogOn {
            get {
                return ResourceManager.GetString("SettingsRunOnLogOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spustit minumalizované.
        /// </summary>
        internal static string SettingsStartMinimized {
            get {
                return ResourceManager.GetString("SettingsStartMinimized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chování.
        /// </summary>
        internal static string SettingsTabPageBehavior {
            get {
                return ResourceManager.GetString("SettingsTabPageBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sítě.
        /// </summary>
        internal static string SettingsTabPageNetworks {
            get {
                return ResourceManager.GetString("SettingsTabPageNetworks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ostatní.
        /// </summary>
        internal static string SettingsTabPageOther {
            get {
                return ResourceManager.GetString("SettingsTabPageOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Časovač.
        /// </summary>
        internal static string SettingsTabPageTimer {
            get {
                return ResourceManager.GetString("SettingsTabPageTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zobrazit.
        /// </summary>
        internal static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to START.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stav.
        /// </summary>
        internal static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto: Aktivováno.
        /// </summary>
        internal static string StatusActivatedAuto {
            get {
                return ResourceManager.GetString("StatusActivatedAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ručně: Aktivováno.
        /// </summary>
        internal static string StatusActivatedManual {
            get {
                return ResourceManager.GetString("StatusActivatedManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto: Deaktivováno.
        /// </summary>
        internal static string StatusDeactivatedAuto {
            get {
                return ResourceManager.GetString("StatusDeactivatedAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ručně: Deaktivováno.
        /// </summary>
        internal static string StatusDeactivatedManual {
            get {
                return ResourceManager.GetString("StatusDeactivatedManual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STOP.
        /// </summary>
        internal static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budiž.
        /// </summary>
        internal static string TimeSpanPickerFrmButtonOk {
            get {
                return ResourceManager.GetString("TimeSpanPickerFrmButtonOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zrušit.
        /// </summary>
        internal static string TimeSpanPickerFrmBuutonCancel {
            get {
                return ResourceManager.GetString("TimeSpanPickerFrmBuutonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Čas.
        /// </summary>
        internal static string TimeSpanPickerFrmFormName {
            get {
                return ResourceManager.GetString("TimeSpanPickerFrmFormName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hodiny.
        /// </summary>
        internal static string TimeSpanPickerFrmLabelHours {
            get {
                return ResourceManager.GetString("TimeSpanPickerFrmLabelHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minuty.
        /// </summary>
        internal static string TimeSpanPickerFrmLabelMinutes {
            get {
                return ResourceManager.GetString("TimeSpanPickerFrmLabelMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vteřiny.
        /// </summary>
        internal static string TimeSpanPickerFrmLabelSeconds {
            get {
                return ResourceManager.GetString("TimeSpanPickerFrmLabelSeconds", resourceCulture);
            }
        }
    }
}
